# -*- coding: utf-8 -*-
"""Onnx_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PZyIWMi0-lmcQGMmLf9FJpfrjS7pVzg
"""

!pip install optimum[onnxruntime] transformers

from google.colab import drive
drive.mount('/content/drive')

MODEL_PATH = "/content/drive/MyDrive/notification_model/final_model"
ONNX_OUTPUT_PATH = "/content/drive/MyDrive/notification_model/distilbert_onnx"

import os
os.makedirs(ONNX_OUTPUT_PATH, exist_ok=True)

from optimum.onnxruntime import ORTModelForSequenceClassification

model = ORTModelForSequenceClassification.from_pretrained(
    MODEL_PATH,
    export=True
)

model.save_pretrained(ONNX_OUTPUT_PATH)

print("ONNX model exported successfully.")

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
tokenizer.save_pretrained(ONNX_OUTPUT_PATH)

print("Tokenizer saved successfully.")

import json
import os

# Because you trained on priority values
label_list = [1, 2, 3, 4]

label_map = {i: label for i, label in enumerate(label_list)}

with open(os.path.join(ONNX_OUTPUT_PATH, "label_map.json"), "w") as f:
    json.dump(label_map, f)

print("Label map saved successfully.")

os.listdir(ONNX_OUTPUT_PATH)

import torch
from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer

model = ORTModelForSequenceClassification.from_pretrained(ONNX_OUTPUT_PATH)
tokenizer = AutoTokenizer.from_pretrained(ONNX_OUTPUT_PATH)

text = "Your order has been shipped."

inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

print("Predicted encoded label:", prediction)

import torch
from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer

model = ORTModelForSequenceClassification.from_pretrained(ONNX_OUTPUT_PATH)
tokenizer = AutoTokenizer.from_pretrained(ONNX_OUTPUT_PATH)

text = "Congratulations! You won a free prize!"

inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

print("Predicted encoded label:", prediction)

"""**QUANTIZATION**"""

!pip install onnxruntime onnxruntime-tools

from onnxruntime.quantization import quantize_dynamic, QuantType

import os

original_model_path = os.path.join(ONNX_OUTPUT_PATH, "model.onnx")
quantized_model_path = os.path.join(ONNX_OUTPUT_PATH, "model_quantized.onnx")

quantize_dynamic(
    model_input=original_model_path,
    model_output=quantized_model_path,
    weight_type=QuantType.QInt8
)

print("Quantization complete!")

import os

original_size = os.path.getsize(original_model_path) / (1024 * 1024)
quantized_size = os.path.getsize(quantized_model_path) / (1024 * 1024)

print(f"Original model size: {original_size:.2f} MB")
print(f"Quantized model size: {quantized_size:.2f} MB")

from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer
import torch
import json
import os

model = ORTModelForSequenceClassification.from_pretrained(
    ONNX_OUTPUT_PATH,
    file_name="model_quantized.onnx"
)

tokenizer = AutoTokenizer.from_pretrained(ONNX_OUTPUT_PATH)

# Load the label map
with open(os.path.join(ONNX_OUTPUT_PATH, "label_map.json"), "r") as f:
    label_map = json.load(f)

text = "Your meeting is scheduled for tomorrow at 10 AM."
inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)
prediction = torch.argmax(outputs.logits, dim=1).item()

# Convert encoded prediction back to original label
predicted_label = label_map[str(prediction)]

print(f"Input text: '{text}'")
print(f"Predicted encoded label: {prediction}")
print(f"Predicted original label: {predicted_label}")

import torch
import json
import os

# Define the OTP text
otp_text = "Your OTP for transaction is 123456. Do not share this code."

# Tokenize the OTP text
inputs_otp = tokenizer(otp_text, return_tensors="pt")

# Get predictions for OTP text
outputs_otp = model(**inputs_otp)
prediction_otp_encoded = torch.argmax(outputs_otp.logits, dim=1).item()
prediction_otp_original = label_map[str(prediction_otp_encoded)]

print(f"Input text (OTP): '{otp_text}'")
print(f"Predicted encoded label (OTP): {prediction_otp_encoded}")
print(f"Predicted original label (OTP): {prediction_otp_original}")

import torch
import json
import os

# Define the delivery text
delivery_text = "Your package is out for delivery and will arrive within the next hour."

# Tokenize the delivery text
inputs_delivery = tokenizer(delivery_text, return_tensors="pt")

# Get predictions for delivery text
outputs_delivery = model(**inputs_delivery)
prediction_delivery_encoded = torch.argmax(outputs_delivery.logits, dim=1).item()
prediction_delivery_original = label_map[str(prediction_delivery_encoded)]

print(f"\nInput text (Delivery): '{delivery_text}'")
print(f"Predicted encoded label (Delivery): {prediction_delivery_encoded}")
print(f"Predicted original label (Delivery): {prediction_delivery_original}")

import torch
import json
import os

text_free_prize = "Congratulations! You won a free prize!"

inputs_free_prize = tokenizer(text_free_prize, return_tensors="pt")
outputs_free_prize = model(**inputs_free_prize)
prediction_free_prize_encoded = torch.argmax(outputs_free_prize.logits, dim=1).item()
prediction_free_prize_original = label_map[str(prediction_free_prize_encoded)]

print(f"\nInput text: '{text_free_prize}'")
print(f"Predicted encoded label: {prediction_free_prize_encoded}")
print(f"Predicted original label: {prediction_free_prize_original}")

import torch
import json
import os

text_seasonal_sale = "Seasonal Sale: Up to 50% off on all items!"

inputs_seasonal_sale = tokenizer(text_seasonal_sale, return_tensors="pt")
outputs_seasonal_sale = model(**inputs_seasonal_sale)
prediction_seasonal_sale_encoded = torch.argmax(outputs_seasonal_sale.logits, dim=1).item()
prediction_seasonal_sale_original = label_map[str(prediction_seasonal_sale_encoded)]

print(f"\nInput text: '{text_seasonal_sale}'")
print(f"Predicted encoded label: {prediction_seasonal_sale_encoded}")
print(f"Predicted original label: {prediction_seasonal_sale_original}")

import torch
import json
import os

text_delivery_low_priority = "Your package is out for delivery and will arrive within the next hour."

inputs_delivery_low_priority = tokenizer(text_delivery_low_priority, return_tensors="pt")
outputs_delivery_low_priority = model(**inputs_delivery_low_priority)
prediction_delivery_low_priority_encoded = torch.argmax(outputs_delivery_low_priority.logits, dim=1).item()
prediction_delivery_low_priority_original = label_map[str(prediction_delivery_low_priority_encoded)]

print(f"\nInput text: '{text_delivery_low_priority}'")
print(f"Predicted encoded label: {prediction_delivery_low_priority_encoded}")
print(f"Predicted original label: {prediction_delivery_low_priority_original}")

import torch
import json
import os
from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer

# Load the quantized model and tokenizer
model = ORTModelForSequenceClassification.from_pretrained(
    ONNX_OUTPUT_PATH,
    file_name="model_quantized.onnx"
)
tokenizer = AutoTokenizer.from_pretrained(ONNX_OUTPUT_PATH)

# Load the label map
with open(os.path.join(ONNX_OUTPUT_PATH, "label_map.json"), "r") as f:
    label_map = json.load(f)

text_coffee_meeting = "Hey \"Are we still meeting for coffee later today?\""

inputs_coffee_meeting = tokenizer(text_coffee_meeting, return_tensors="pt")
outputs_coffee_meeting = model(**inputs_coffee_meeting)
prediction_coffee_meeting_encoded = torch.argmax(outputs_coffee_meeting.logits, dim=1).item()
prediction_coffee_meeting_original = label_map[str(prediction_coffee_meeting_encoded)]

print(f"\nInput text: '{text_coffee_meeting}'")
print(f"Predicted encoded label: {prediction_coffee_meeting_encoded}")
print(f"Predicted original label: {prediction_coffee_meeting_original}")

import torch
import json
import os
from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer

# Load the quantized model and tokenizer
model = ORTModelForSequenceClassification.from_pretrained(
    ONNX_OUTPUT_PATH,
    file_name="model_quantized.onnx"
)
tokenizer = AutoTokenizer.from_pretrained(ONNX_OUTPUT_PATH)

# Load the label map
with open(os.path.join(ONNX_OUTPUT_PATH, "label_map.json"), "r") as f:
    label_map = json.load(f)

text_dinner_invite = "Hey, are you coming for dinner tonight?"

inputs_dinner_invite = tokenizer(text_dinner_invite, return_tensors="pt")
outputs_dinner_invite = model(**inputs_dinner_invite)
prediction_dinner_invite_encoded = torch.argmax(outputs_dinner_invite.logits, dim=1).item()
prediction_dinner_invite_original = label_map[str(prediction_dinner_invite_encoded)]

print(f"\nInput text: '{text_dinner_invite}'")
print(f"Predicted encoded label: {prediction_dinner_invite_encoded}")
print(f"Predicted original label: {prediction_dinner_invite_original}")

